apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopkaro-ingress
  namespace: shopkaro   
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - shopkaro.letsdeployit.com
    secretName: shopkaro-tls-secret  # Cert-Manager will manage this
  rules:
  - host: shopkaro.letsdeployit.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shopkaro-service
            port:
              number: 80

